### ISSUE TITLE
Potential caching issue

### ISSUE THREAD

**Issue by robmarshdev** [seanmtracey/CineList-API#16]
Hi Sean,

I've been querying your API to access my local cinema listings today (06/08/2017) and have just noticed that it appears to be returning the results from yesterday (05/08/2017). If I set the day to 1 it will return tomorrows dates and so I have no way to access the listings today. If you query the FaF api directly it seems to return the correct results so I would assume that it must be caching the results somewhere.

If it's useful my cinema is Vue, Hull and has ID 9669 and I used the following website to prove that it is displaying yesterday's viewings...

https://www.view.co.uk/hull/v/vue-cinema-hull/cinema-listings

Let me know if there is any other information you need.

Thanks,
Rob

**Comment by seanmtracey** [comment]
I think I've fixed this. CineList heavily caches the results it returns and it's meant to empty the cache at midnight and repeat it's scraping with the new times in their place. Please do let me know if this is still an issue, and I'll double check, otherwise I'll close the issue in a fortnight `2018-03-02`.
