### ISSUE TITLE
FindAnyFilm.com is unreliable - request alternative source

### ISSUE THREAD

**Issue by theshillito** [seanmtracey/CineList-API#17]
The use of FindAnyFilm.com is getting worse by the day. My regular cinema (Odeon Northwich Barons Quay) isn't listed, times are often wrong and they don't respond to my emails. It also doesn't list many Bollywood or other non-English films, leading to the listings being incomplete. I've wrote an application that uses the CineList API, but I can't trust its output.

**Comment by seanmtracey** [comment]
Hi, thanks for getting in touch. Sorry about the delay in getting back to you.

I'd love to use something other than Find Any Film, but regrettably, it's the only source I'm aware of that's anywhere close to being a complete repository of both cinemas and times in the UK.

CineList was born of my frustration that Find Any Film is a poor way to lookup times, but until someone in the cinema industry comes along and creates another one - or a standard appears for interfacing with the different cinema chains, I'm afraid we're stuck with it.

What app did you build? I love to see applications that use CineList as their data source.

**Comment by theshillito** [comment]
That's a shame, but understandable. Thanks for getting back to me. Considering all my nearby cinemas are Odeons, including the one that isn't on Find Any Film, I may have to look into a way of getting specifically Odeon listings in place of CineList.

The app I made isn't anything special. It just outputs film times for my nearest (listed) cinema in one of several frames on a dashboard screen I set up in my home. I'm still messing about with layouts and styles, so it's very basic at the moment (so please don't be mad that it looks kinda ugly at the moment haha).
![2017-09-27 07 17 25](https://user-images.githubusercontent.com/1828418/31173773-be45aea6-a900-11e7-85d2-d626e1a5404a.jpg)

**Comment by seanmtracey** [comment]
No worries! It's great, I've always wanted to set up a dashboard in my home, but I can never find the time 😅

**Comment by colons** [comment]
I was using the CineList API and [GeekTool](https://www.tynsoe.org/v2/geektool/) to put my local Odeon's listings on my desktop, but after an inaccuracy ended up with me showing up to a film I wanted to see a full 24 hours after it was actually on show, I caved and implemented [my own, CineList-compatible API](https://github.com/colons/odeon-scraper) so that it wouldn't happen again.

I don't know if a Python-based scraper that's specific to a particular chain is any use to you, but it exists if you want to use it, and it has an API if you don't want to run it locally.

**Comment by seanmtracey** [comment]
I think a long term solution (if nothing else comes along) is to have individual scrapers for each chain, but that involves a great deal of work and maintenance that I just don't have time to do :(

Fun fact: The very first version of CineList was powered by Python (Beautiful Soup). I moved to Node.js about a year later.

As for inaccuracies, that _might_ have been caused by CineList being a little overzealous on caching, I'll take a look into that at some point in the next few days.
